server:
  compression:
    enabled: true
  # Default port
  port: 8080
  # Enable graceful shutdown - Server will wait for active request to finish
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
# Spring Configuration
spring:
  application:
    name: distributed-cache
  profiles:
    active: local
# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
# Redis Configuration
cache:
  redis:
    config:
      connection-timeout: 1s
      read-timeout: 1s
      max-idle-pool: 8
      max-total-pool: 8
      max-wait: 1s
      min-idle-pool: 0
      retry: 1
      nodes:
        - "localhost:7100"
        - "localhost:7101"
        - "localhost:7102"
        - "localhost:7103"
        - "localhost:7104"
        - "localhost:7105"
    ttl: 1m
    compression-algorithm: SNAPPY
